USE RIO_IPS

ALTER TABLE DT_DOCUMENTS_TABLES ADD DOCUMENT_GROUP_TABLE_NAME varchar(100)
ALTER TABLE DT_DOCUMENTS_TABLES ADD DOCUMENT_ERRORS_TABLE_NAME varchar(100)
ALTER TABLE DT_DOCUMENTS_TABLES ADD DOCUMENT_TABLE_ERRORS_TYPE int


ALTER TABLE DT_DOCUMENTS_TABLES_COLUMNS ADD COLUMN_TABLE_NAME varchar(50)
ALTER TABLE DT_DOCUMENTS_TABLES_COLUMNS ADD COLUMN_FIELD_NAME varchar(50)
ALTER TABLE DT_DOCUMENTS_TABLES_COLUMNS ADD COLUMN_FIXED_FLAG int
ALTER TABLE DT_DOCUMENTS_TABLES_COLUMNS ADD COLUMN_COLOR int


ALTER TABLE DT_PAGE_FOLDERS ADD PAGE_FOLDER_PROJECT_FILE_ID int
CREATE NONCLUSTERED INDEX [PAGE_FOLDER_PROJECT_FILE_ID_INDEX] ON [dbo].[DT_PAGE_FOLDERS]
(
[PAGE_FOLDER_PROJECT_FILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)


ALTER TABLE DT_DOC_TYPES ADD IGNORE_STRUCTURE_PAGE_TYPE_FLAG int


ALTER TABLE DT_PAGE_TYPE_SAMPLES ADD ID_USER_CREATE int
ALTER TABLE DT_PAGE_TYPE_SAMPLES ADD ID_USER_MODIFY int
ALTER TABLE DT_PAGE_TYPE_SAMPLES ADD DATE_CREATE DateTime
ALTER TABLE DT_PAGE_TYPE_SAMPLES ADD DATE_MODIFY DateTime

ALTER TABLE DT_PROJECT_FILES_ATTRIBUTES ADD ATTRIBUTE_CONF int