use DELICE_TECH_PROCESS
 
--DISABLE TRIGGER [trg_loggingDDLModify] ON DATABASE
  
set nocount on
 
-- очищаем БД от лишних пользователей
declare @sql nvarchar(1000)
declare user_cur cursor local
for
select name from sys.sysusers where issqlrole = 0 and status > 0
open user_cur
fetch next from user_cur into @sql
while @@FETCH_STATUS = 0
    begin
        set @sql  = 'drop user [' + @sql + ']'     
         
        begin try
            exec sp_executesql @sql            
        end try
 
        begin catch
            print error_message()
            return
        end catch
         
 
        fetch next from user_cur into @sql
    end
close user_cur
deallocate user_cur
 
-----------
 
 
truncate table DT_OCR_SETTINGS_PROCESSES DBCC CHECKIDENT ('DT_OCR_SETTINGS_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_OBJECTS_DETECT_PROCESSES DBCC CHECKIDENT ('DT_OBJECTS_DETECT_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CONNECTION_SESSIONS DBCC CHECKIDENT ('DT_CONNECTION_SESSIONS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CONNECTION_LOGINS DBCC CHECKIDENT ('DT_CONNECTION_LOGINS', reseed, 1) WITH NO_INFOMSGS
 
truncate table DT_TECH_PROCESSES DBCC CHECKIDENT ('DT_TECH_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_COMPRESS_TASKS DBCC CHECKIDENT ('DT_COMPRESS_TASKS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CLEAR_SETTINGS DBCC CHECKIDENT ('DT_CLEAR_SETTINGS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CLEAR_LOG DBCC CHECKIDENT ('DT_CLEAR_LOG', reseed, 1) WITH NO_INFOMSGS
 
  
truncate table DT_CODES_LOG DBCC CHECKIDENT ('DT_CODES_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CODES_2_LIST DBCC CHECKIDENT ('DT_CODES_2_LIST', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CODES_2_LIST_ARCHIVE DBCC CHECKIDENT ('DT_CODES_2_LIST_ARCHIVE', reseed, 1) WITH NO_INFOMSGS
 
truncate table DT_CODES_LIST DBCC CHECKIDENT ('DT_CODES_LIST', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CODES_LIST_ARCHIVE
truncate table DT_CODES_LOG DBCC CHECKIDENT ('DT_CODES_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CODES_PROCESSES DBCC CHECKIDENT ('DT_CODES_PROCESSES', reseed, 1) WITH NO_INFOMSGS
delete from DT_CODES_SETTINGS where PROJECT_ID <> 1
--DBCC CHECKIDENT ('DT_CODES_SETTINGS', reseed, 2) WITH NO_INFOMSGS
truncate table DT_CODES_SETTINGS_PROCESSES DBCC CHECKIDENT ('DT_CODES_SETTINGS_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CODES_STATS_TITLES DBCC CHECKIDENT ('DT_CODES_STATS_TITLES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CODES_TASKS DBCC CHECKIDENT ('DT_CODES_TASKS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_CODES_TASKS_ARCHIVE
truncate table DT_CODES_TOTAL_STATS DBCC CHECKIDENT ('DT_CODES_TOTAL_STATS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_COPY_FOLDERS DBCC CHECKIDENT ('DT_COPY_FOLDERS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_DDL_MODIFY_LOG DBCC CHECKIDENT ('DT_DDL_MODIFY_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_FILES DBCC CHECKIDENT ('DT_FILES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_FILES_ARCHIVE
truncate table DT_FILES_TASKS DBCC CHECKIDENT ('DT_FILES_TASKS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_FOLDERS DBCC CHECKIDENT ('DT_FOLDERS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_FOLDERS_ARCHIVE
truncate table DT_INDEXING_LOG DBCC CHECKIDENT ('DT_INDEXING_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_INDEXING_PROCESSES DBCC CHECKIDENT ('DT_INDEXING_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_INDEXING_TASKS DBCC CHECKIDENT ('DT_INDEXING_TASKS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_MAIN_COPY_PROCESSES DBCC CHECKIDENT ('DT_MAIN_COPY_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_OCR_PROCESSES DBCC CHECKIDENT ('DT_OCR_PROCESSES', reseed, 1) WITH NO_INFOMSGS
delete from DT_OCR_SETTINGS where PROJECT_ID <> 1
--DBCC CHECKIDENT ('DT_OCR_SETTINGS', reseed, 2) WITH NO_INFOMSGS
truncate table DT_OCR_STATS_TITLES DBCC CHECKIDENT ('DT_OCR_STATS_TITLES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_OCR_TASKS DBCC CHECKIDENT ('DT_OCR_TASKS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_OCR_TASKS_ARCHIVE
truncate table DT_OCR_TOTAL_STATS DBCC CHECKIDENT ('DT_OCR_TOTAL_STATS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_PARTS DBCC CHECKIDENT ('DT_PARTS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_PARTS_LOG DBCC CHECKIDENT ('DT_PARTS_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_PDF_LIST DBCC CHECKIDENT ('DT_PDF_LIST', reseed, 1) WITH NO_INFOMSGS
truncate table DT_PDF_LIST_ARCHIVE
truncate table DT_PDF_LOG DBCC CHECKIDENT ('DT_PDF_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_PDF_PROCESSES DBCC CHECKIDENT ('DT_PDF_PROCESSES', reseed, 1) WITH NO_INFOMSGS
delete from DT_PDF_SETTINGS where PROJECT_ID <> 1
--DBCC CHECKIDENT ('DT_PDF_SETTINGS', reseed, 2) WITH NO_INFOMSGS
truncate table DT_PDF_TASKS DBCC CHECKIDENT ('DT_PDF_TASKS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_PDF_TASKS_ARCHIVE
truncate table DT_PICTURES_SORT_PROCESSES DBCC CHECKIDENT ('DT_PICTURES_SORT_PROCESSES', reseed, 1) WITH NO_INFOMSGS
--DBCC CHECKIDENT ('DT_PICTURES_SORT_SETTINGS', reseed, 2) WITH NO_INFOMSGS
truncate table DT_PRE_OCR_PROCESSES DBCC CHECKIDENT ('DT_PRE_OCR_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_PRE_OCR_TASKS DBCC CHECKIDENT ('DT_PRE_OCR_TASKS', reseed, 1) WITH NO_INFOMSGS
delete from DT_PROJECT_TASKS where PROJECT_ID <> 1
delete from DT_PROJECTS where PROJECT_ID <> 1
--DBCC CHECKIDENT ('DT_PROJECTS', reseed, 2) WITH NO_INFOMSGS
truncate table DT_SOURCE_FILES DBCC CHECKIDENT ('DT_SOURCE_FILES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_SOURCE_PICTURES DBCC CHECKIDENT ('DT_SOURCE_PICTURES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_TASK_MESSAGES DBCC CHECKIDENT ('DT_TASK_MESSAGES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_TASK_SERVICES DBCC CHECKIDENT ('DT_TASK_SERVICES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_TECH_PROCESSES DBCC CHECKIDENT ('DT_TECH_PROCESSES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_TASKS_CONTROL DBCC CHECKIDENT ('DT_TASKS_CONTROL', reseed, 1) WITH NO_INFOMSGS
truncate table DT_TASKS_PROCESSES_PROJECTS DBCC CHECKIDENT ('DT_TASKS_PROCESSES_PROJECTS', reseed, 1) WITH NO_INFOMSGS
truncate table DT_MAIN_INI_FILES DBCC CHECKIDENT ('DT_MAIN_INI_FILES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_MAIN_COPY_MESSAGES DBCC CHECKIDENT ('DT_MAIN_COPY_MESSAGES', reseed, 1) WITH NO_INFOMSGS
truncate table DT_OBJECTS_DETECT_TASKS DBCC CHECKIDENT ('DT_OBJECTS_DETECT_TASKS', reseed, 1) WITH NO_INFOMSGS
delete from DT_PICTURES_SORT_SETTINGS where PROJECT_ID <> 1
truncate table DT_SERVICE_LIBRARIES_LOG DBCC CHECKIDENT ('DT_SERVICE_LIBRARIES_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_SERVICE_LIBRARIES_FILES_LOG DBCC CHECKIDENT ('DT_SERVICE_LIBRARIES_FILES_LOG', reseed, 1) WITH NO_INFOMSGS
truncate table DT_SERVICE_LIBRARIES DBCC CHECKIDENT ('DT_SERVICE_LIBRARIES', reseed, 1) WITH NO_INFOMSGS
--DBCC SHRINKDATABASE(N'DELICE_TECH_PROCESS' )
--DBCC SHRINKFILE (N'DELICE_TECH_PROCESS_log' , 0, TRUNCATEONLY)

--declare @IPS_BK_NAME nvarchar(1000) = N'D:\SQL_BK\DELICE_TECH_PROCESS_etalon_2_' + replace(replace(replace(replace(convert(varchar(100), GetDate(), 121), '-', ''), ' ', ''), ':', ''), '.', '') + '.bak'
--BACKUP DATABASE [DELICE_TECH_PROCESS] TO  DISK = @IPS_BK_NAME WITH NOFORMAT,
--INIT,  NAME = N'DELICE_TECH_PROCESS-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10


--ENABLE TRIGGER [trg_loggingDDLModify] ON DATABASE
 
