//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ocrcfg.rc
//
#define IDC_OCRCFG_STATIC_STAGE         57010
#define IDC_OCRCFG_PROGRESS             57011
#define IDC_OCRCFG_STATIC_STATUS        57012
#define IDC_OCRCFG_CHECK_SKIP           57013
#define IDC_OCRCFG_ICON                 57014
#define IDC_OCRCFG_DEPLOYRPT_ICON       57014
#define IDC_OCRCFG_CLICK_NEXT           57015
#define IDC_OCRCFG_WELCOME_STATIC_TITLE 57020
#define IDC_OCRCFG_WELCOME_RADIO_DEFAULTXML 57021
#define IDC_OCRCFG_WELCOME_EDIT_CONFIGFILEPATH 57022
#define IDC_OCRCFG_WELCOME_BUTTON_BROWSE 57023
#define IDC_OCRCFG_WELCOME_RADIO_CONFIGXML 57024
#define IDC_OCRCFG_WELCOME_RADIO_SELECTSERVERS 57025
#define IDC_OCRCFG_WELCOME_RADIO_SOFT_LIBRARY 57026
#define IDC_OCRCFG_WELCOME_RADIO_DCOM   57027
#define IDC_OCRCFG_CREDENTIALS_EDIT_LOGIN 57028
#define IDC_OCRCFG_CREDENTIALS_BUTTON_SELECT 57029
#define IDC_OCRCFG_CREDENTIALS_EDIT_PASSWORD 57030
#define IDC_OCRCFG_CREATEFOLDER_EDIT_PROJECT_FOLDER 57031
#define IDC_OCRCFG_CREATEFOLDER_BUTTON_BROWSE_PROJECT 57032
#define IDC_OCRCFG_CREATEFOLDER_EDIT_SCANS_FOLDER 57033
#define IDC_OCRCFG_CREATEFOLDER_BUTTON_BROWSE_SCANS 57034
#define IDC_OCRCFG_CREATEDB_COMBO_SQLSERVER 57035
#define IDC_OCRCFG_CREATEDB_EDIT_DATABASE 57036
#define IDC_OCRCFG_CREATEDB_EDIT_DATABASE_2 57037
#define IDC_OCRCFG_APPLYSCRIPTS_LIST    57040
#define IDC_OCRCFG_REGJOBS_LIST         57041
#define IDC_OCRCFG_REGSVC_LIST          57042
#define IDC_OCRCFG_DEPLOYRPT_COMBO_REPORTSERVER 57051
#define IDC_OCRCFG_DEPLOYRPT_COMBO_SQLSERVER 57052
#define IDC_OCRCFG_DEPLOYRPT_EDIT_FOLDER 57053
#define IDC_OCRCFG_DEPLOYRPT_STATIC_STATUS_TEXT 57054
#define IDC_OCRCFG_LICENSE_EDIT_KEY     57059
#define IDC_OCRCFG_FINISH_STATIC_TITLE  57060
#define IDC_OCRCFG_FINISH_EDIT_INFO     57061
#define IDC_OCRCFG_FINISH_CHECK_UNINSTALL 57062
#define IDC_OCRCFG_FINISH_ADDITIONAL    57063
#define IDC_OCRCFG_CONFIGXML_EDIT_CONFIGFILEPATH 57068
#define IDC_OCRCFG_CONFIGXML_BUTTON_BROWSE 57069
#define IDC_OCRCFG_SELECTSERVERS_COMBO_REPORTSERVER 57070
#define IDC_OCRCFG_SELECTSERVERS_COMBO_SQLSERVER 57072
#define IDC_OCRCFG_SELECTSERVERS_COMBO_DATABASE 57073
#define IDC_OCRCFG_SELECTSERVERS_COMBO_FOLDER 57074
#define IDC_OCRCFG_SELECTSERVERS_BUTTON_UPDATE_WEBFOLDERS 57075
#define IDC_OCRCFG_SELECTSERVERS_BUTTON_UPDATE_DATABASES 57076
#define IDC_OCRCFG_SELECTSERVERS_STATUS_TEXT 57077
#define IDC_OCRCFG_SOFTLIBRARY_COMBO_SQLSERVER 57078
#define IDC_OCRCFG_SOFTLIBRARY_EDIT_DATABASE 57079
#define IDC_OCRCFG_SOFTLIBRARY_RADIO_EXPORT 57080
#define IDC_OCRCFG_SOFTLIBRARY_RADIO_IMPORT 57081
#define IDC_OCRCFG_SOFTLIBRARY_EDIT_XMLFILEPATH 57082
#define IDC_OCRCFG_SOFTLIBRARY_BUTTON_BROWSE 57083
#define IDC_OCRCFG_DCOM_EDIT_LOGIN      57085


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         57100
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
