USE RIO_IPS

CREATE TABLE [dbo].[DT_PROJECT_FILES_ATTRIBUTES_MESSAGES](
[PROJECT_FILE_ATTRIBUTE_MESSAGE_ID] [int] IDENTITY(1,1) NOT NULL,
[PROJECT_FILE_ATTRIBUTE_ID] [int] NULL,
[MESSAGE_TEXT] [varchar](1000) NULL,
[MESSAGE_DATE] [datetime] NULL,
[MESSAGE_SHOW_FLAG] [int] NULL,
CONSTRAINT [PK_DT_PROJECT_FILE_ATTRIBUTE_MESSAGES] PRIMARY KEY CLUSTERED
(
[PROJECT_FILE_ATTRIBUTE_MESSAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_DT_PROJECT_FILES_ATTRIBUTES_MESSAGES] ON [dbo].[DT_PROJECT_FILES_ATTRIBUTES_MESSAGES]
(
[PROJECT_FILE_ATTRIBUTE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


CREATE TABLE [dbo].[DT_ERROR_CODES](
[ERROR_CODE_ID] [int] NOT NULL,
[ERROR_NAME] [varchar](100) NULL,
[ERROR_DESCRIPTION] [varchar](800) NULL,
CONSTRAINT [PK_DT_ERROR_CODES] PRIMARY KEY CLUSTERED
(
[ERROR_CODE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--------------------------------

CREATE TABLE [dbo].[DT_PAGE_TYPE_SAMPLES_ATTRS_HISTORY](
[KEY_ATTR_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
[PAGE_TYPE_SAMPLE_HISTORY_ID] [int] NULL,
[PAGE_TYPE_SAMPLE_ID] [int] NULL,
[DOC_ATTR_ID] [int] NULL,
[KEY_ATTR_LEFT] [int] NULL,
[KEY_ATTR_TOP] [int] NULL,
[KEY_ATTR_WIDTH] [int] NULL,
[KEY_ATTR_HEIGHT] [int] NULL,
[ATTR_LEFT] [int] NULL,
[ATTR_TOP] [int] NULL,
[ATTR_WIDTH] [int] NULL,
[ATTR_HEIGHT] [int] NULL,
[KEY_ATTR_TEXT] [varchar](1000) NULL,
[SMART_VIEW_KEYWORDS] [varchar](1000) NULL,
[SMART_VIEW_LEFT] [int] NULL,
[SMART_VIEW_TOP] [int] NULL,
[SMART_VIEW_WIDTH] [int] NULL,
[SMART_VIEW_HEIGHT] [int] NULL,
[SMART_VIEW_KEYWORDS_LEFT] [int] NULL,
[SMART_VIEW_KEYWORDS_TOP] [int] NULL,
[SMART_VIEW_KEYWORDS_WIDTH] [int] NULL,
[SMART_VIEW_KEYWORDS_HEIGHT] [int] NULL,
[KEY_ATTR_CELL_FLAG] [int] NULL,
[ATTR_CELL_FLAG] [int] NULL,
[KEY_ATTR_FUNCTION_NUMBER] [int] NULL,
CONSTRAINT [PK_DT_SAMPLES_ATTRS_HISTORY] PRIMARY KEY CLUSTERED
(
[KEY_ATTR_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[DT_PAGE_TYPE_SAMPLES_BLOCKS_HISTORY](
[PAGE_TYPE_SAMPLE_BLOCK_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
[PAGE_TYPE_SAMPLE_HISTORY_ID] [int] NULL,
[PAGE_TYPE_SAMPLE_ID] [int] NULL,
[BLOCK_LEFT] [int] NULL,
[BLOCK_TOP] [int] NULL,
[BLOCK_WIDTH] [int] NULL,
[BLOCK_HEIGHT] [int] NULL,
CONSTRAINT [PK_DT_PAGE_TYPE_SAMPLES_BLOCKS_HISTORY] PRIMARY KEY CLUSTERED
(
[PAGE_TYPE_SAMPLE_BLOCK_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[DT_PAGE_TYPE_SAMPLES_BLOCKS_KEYWORDS_HISTORY](
[PAGE_TYPE_SAMPLE_BLOCK_WORD_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
[PAGE_TYPE_SAMPLE_HISTORY_ID] [int] NULL,
[PAGE_TYPE_SAMPLE_BLOCK_ID] [int] NULL,
[BLOCK_KEYWORDS] [varchar](1000) NULL,
[KEYWORDS_NUMBER] [varchar](1000) NULL,
CONSTRAINT [PK_DT_PAGE_TYPES_BLOCKS_KEYWORDS_HISTORY] PRIMARY KEY CLUSTERED
(
[PAGE_TYPE_SAMPLE_BLOCK_WORD_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[DT_PAGE_TYPE_SAMPLES_HISTORY](
[PAGE_TYPE_SAMPLE_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
[PAGE_TYPE_SAMPLE_ID] [int] NOT NULL,
[PAGE_TYPE_SAMPLE_FILE_NAME] [varchar](1000) NULL,
[FILE_ID] [int] NULL,
[PAGE_TYPE_ID] [int] NULL,
[PAGE_TYPE_SAMPLE_NAME] [varchar](200) NULL,
[PAGE_TYPE_SAMPLE_ORDER_NUMBER] [int] NULL,
[PAGE_TYPE_SAMPLE_OPERATOR_ID] [int] NULL,
[PAGE_TYPE_SAMPLE_DATE] [datetime] NULL,
[CLASSIFICATION_SAMPLE_FLAG] [int] NULL,
[INDEXING_SAMPLE_FLAG] [int] NULL,
[PAGE_TITLE] [varchar](1000) NULL,
[TYPICAL_FLAG] [int] NULL,
[PICTURE_WIDTH] [int] NULL,
[PICTURE_HEIGHT] [int] NULL,
[HOCR_LEFT] [int] NULL,
[HOCR_TOP] [int] NULL,
[HOCR_WIDTH] [int] NULL,
[HOCR_HEIGHT] [int] NULL,
[PAGE_TYPE_SAMPLE_AREA_FLAG] [int] NULL,
[PAGE_TYPE_CODE_KEY_WORDS_FLAG] [int] NULL,
[PAGE_TYPE_CODE_KEY_WORDS_MASK] [varchar](50) NULL,
[PAGE_TYPE_SAMPLE_TYPE] [int] NULL,
[ID_USER_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[ID_USER_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
CONSTRAINT [PK_DT_PAGE_TYPE_SAMPLES_HISTORY] PRIMARY KEY CLUSTERED
(
[PAGE_TYPE_SAMPLE_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[DT_PAGE_TYPE_SAMPLES_KEY_LINKS_HISTORY](
[PAGE_TYPE_SAMPLE_KEY_LINK_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
[PAGE_TYPE_SAMPLE_HISTORY_ID] [int] NULL,
[PAGE_TYPE_SAMPLE_ID] [int] NULL,
[DOC_ATTR_ID] [int] NULL,
[KEY_LINK_LEFT] [int] NULL,
[KEY_LINK_TOP] [int] NULL,
[KEY_LINK_WIDTH] [int] NULL,
[KEY_LINK_HEIGHT] [int] NULL,
[KEY_LINK_TEXT] [varchar](100) NULL,
[KEY_LINK_FLAG] [int] NULL,
CONSTRAINT [PK_DT_PAGE_TYPE_SAMPLES_KEY_LINKS_HISTORY] PRIMARY KEY CLUSTERED
(
[PAGE_TYPE_SAMPLE_KEY_LINK_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[DT_PAGE_TYPE_SAMPLES_KEYWORDS_HISTORY](
[KEYWORD_HISTORY_ID] [int] IDENTITY(1,1) NOT NULL,
[PAGE_TYPE_SAMPLE_HISTORY_ID] [int] NULL,
[PAGE_TYPE_SAMPLE_ID] [int] NULL,
[KEYWORD_STRING] [varchar](100) NULL,
[KEYWORD_LEFT] [int] NULL,
[KEYWORD_TOP] [int] NULL,
[KEYWORD_WIDTH] [int] NULL,
[KEYWORD_HEIGHT] [int] NULL,
[KEYWORD_TYPE] [int] NULL,
CONSTRAINT [PK_DT_PAGE_SAMPLES_KEYWORDS_HISTORY] PRIMARY KEY CLUSTERED
(
[KEYWORD_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

